### ISSUE TITLE
restore application UI state

### ISSUE THREAD

**Issue by maximburdiean** [turelsminion/fintech_test_app#1]
android:launchMode="singleTask"   

1. перейти  на экран счёта, 
2. выйти на экран home 
3. вернуться в приложение, 

expected: мы находимся на экране счёта
actual: мы оказывемся на экране со всеми счетами

При возвращении в приложение нужно оказыватся на том же экране, откуда пользователь "покинул" приложение.

**Comment by turelsminion** [comment]
уже пофиксил
