### ISSUE TITLE
underused butterknife

### ISSUE THREAD

**Issue by maximburdiean** [turelsminion/fintech_test_app#2]
Можноли использовать ButterKnife в таких случаях https://github.com/turelsminion/fintech_test_app/blob/7b49920c3b6185f34b0ff7359f1cb26150208cd4/FinTechTestApp/app/src/main/java/com/fintech/testapp/activities/BankAccountsAdapter.java#L74 ?

**Comment by turelsminion** [comment]
Можно и уже добавил.
